### PR TITLE
Add travis support #10

### LINKED ISSUE #10: Run tests through trevis

### PR DESCRIPTION
**Pull request by evilr00t**
Simple travis check if package can be installed - also adds checks for flake8

https://travis-ci.org/evilr00t/python-loggable-decorator/jobs/595762539

Fixes #10

### CODE REVIEW

**Comment by luiscoms** [comment]
Please, update your branch

**Comment by evilr00t** [comment]
@luiscoms you mean? it's failing because #9 needs to be merged first.

**Comment by evilr00t** [comment]
@luiscoms fixed as well.

**Comment by luiscoms** [comment]
Tests are not passing

**Comment by evilr00t** [comment]
That should be fixed now.

**Pull request merged**
