### PR TITLE
Fix flake8 issues #6

### PR DESCRIPTION
**Pull request by evilr00t**
That should fix issue #6

### CODE REVIEW

**Comment by luiscoms** [comment]
It should pass all tests

**Comment by evilr00t** [comment]
oops - my bad. will fix that in a second.

**Comment by evilr00t** [comment]
@luiscoms that should be fine now.

**Comment by luiscoms** [comment]
This branch is outdated too

**Comment by evilr00t** [comment]
Updated.

**Comment by luiscoms** [comment]
@evilr00t Cause you removed `loggable/__init__.py` code, tests are not passing. You can include `# noqa` clause on that line

**Comment by evilr00t** [comment]
I don't like idea of importing everything in the `__init__.py` when it's not needed. I've fixed unittests.

**Pull request merged**
